### ISSUE TITLE
How to evaluate the model?

### ISSUE THREAD

**Issue by krishnamrith12** [kzhai/PyAdaGram#1]
Hi once the model is genenrated, how do we evaluate the model? What would be object attributes that I can use to access elements in the pickle file.

**Comment by kzhai** [comment]
Normally, you want to evaluate the precision/recall/F-1 score of the
extracted adaptor grammar. For every data, adaptor grammar will give you a
parse tree, you can extract the chunks and evaluate the model.

Best,
Ke

**Comment by krishnamrith12** [comment]
Can you please provide the description for running **launch_test.py** as well. Precisely, Once I get the pickle file (the model), how do I obtain parse tree for new test sentences?

Does the output in **export_aggregated_adaptor_grammar method** be used to load the same as grammar in NLTK or any other library/tool and then use the same as a CFG to evaluate the grammar?

**Comment by kzhai** [comment]
Hi, Amrith,

I have added some description on launch_test.py. At any time, you can
always run "python -m launch_test -h" to get help for the script.
The data_directory should be the directory of input data (containing
train.dat and test.dat), and the model_directory should be the directory
containing the pickle files.

Best,
Ke

**Comment by krishnamrith12** [comment]
Thanks. that will be really helpful.
