### ISSUE TITLE
output the parse tree with the adaptor grammar for test sentence

### ISSUE THREAD

**Issue by unnikrishnanta** [kzhai/PyAdaGram#2]
While using test_launch, how can I obtain the parse tree for a given test sentence? Currently, no parse tree as such is provided. Also, it will be helpful if you can show, how to calculate the probability/confidence of the obtained parse tree?

**Comment by krishnamrith12** [comment]
It seems the log likelihood and non-terminals can be output from the e_step() method. But I could not figure out a way to obtain the parse tree. Any update on this would be helpful

**Comment by kzhai** [comment]
Hi, Amrith,

I am currently doing international traveling attending SIGIR. I will take a
look at the issue when I get back. Thanks.

Best,
Ke

**Comment by kzhai** [comment]
Hi, Amrith,

I think the code block you are looking for is at
https://github.com/kzhai/PyAdaGram/blob/master/hybrid.py#L807, where the
function _sample_tree() would return the parse tree in the format of a list
of grammar productions. You could try to print out them for reference. Let
me know if that helps.

Best,
Ke

**Comment by krishnamrith12** [comment]
Thanks Zhai. This was really helpful for calculating log-likelihood and perplexity.
